### ISSUE TITLE
install fails with missing CRD's and also install id

### ISSUE THREAD

**Issue by debianmaster** [cape-sh/cape#8]
**Describe the bug**

**Kubernetes version**
v1.18.6+k3s1

**To Reproduce**
1. goto cape.sh 
2. login
3. create new installation
4. try install steps
5. install fails with missing CRD's and also install id

**Expected behavior**
cape should be installed

![Screenshot 2021-01-21 at 10 07 17 PM](https://user-images.githubusercontent.com/1439169/105453925-ea5e4200-5c35-11eb-93f8-2a8367155c6b.png)

**Comment by debianmaster** [comment]
@badoet  @mateeyow

**Comment by mateeyow** [comment]
We have not yet published the new installation instructions. There should be a new instruction. 
kubectl apply -f https://cape.sh/install/crds.yaml before applying the simple.yaml. this is to solve the issue of kubernetes complaining CRD Organization not found when we combine them all on a single yaml file.

**Comment by mateeyow** [comment]
@badoet This issue is resolved, can help close. Thanks.
